import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');
const data = JSON.parse(read('data/milaura-owned-stones.json'));

const expectedCollections = new Set([
  '/collections/bracelets-amethyste',
  '/collections/bracelets-quartz-rose',
  '/collections/bracelets-aigue-marine',
  '/collections/bracelets-cornaline',
  '/collections/bracelets-onyx',
  '/collections/bracelets-sodalite',
  '/collections/bracelets-aventurine-verte',
  '/collections/bracelets-lapis-lazuli'
]);

const generatedFiles = [
  'snippets/milaura-owned-selector-cards.liquid',
  'snippets/milaura-owned-care-rows.liquid',
  'snippets/milaura-owned-birth-months.liquid',
  'snippets/milaura-owned-atlas-entries.liquid'
];

const sectionFiles = [
  'sections/milaura-owned-stone-selector.liquid',
  'sections/milaura-owned-stone-care.liquid',
  'sections/milaura-owned-birthstones.liquid',
  'sections/milaura-owned-stone-atlas.liquid',
  'sections/milaura-owned-study.liquid'
];

const heroSnippet = 'snippets/milaura-owned-hero.liquid';
const heroVariants = ['stone-finder', 'stone-care', 'birthstones', 'stone-atlas', 'study'];
const heroAssets = heroVariants.flatMap((variant) => [
  `assets/milaura-hero-editorial-owned-${variant}-desktop.webp`,
  `assets/milaura-hero-editorial-owned-${variant}-mobile.webp`
]);

test('dataset covers the eight commercial stones and every birth month', () => {
  assert.equal(data.stones.length, 8);
  assert.deepEqual(data.birthstones.map((item) => item.month), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  assert.deepEqual(new Set(data.stones.map((stone) => stone.primary_collection_url)), expectedCollections);
});

test('every stone has source-backed care and a real Shopify image', () => {
  const sourceIds = new Set(data.sources.map((source) => source.id));
  for (const stone of data.stones) {
    assert.match(stone.image_url, /^https:\/\/cdn\.shopify\.com\//);
    assert.ok(stone.image_alt.length > 8);
    assert.ok(stone.source_ids.length > 0);
    for (const sourceId of stone.source_ids) assert.ok(sourceIds.has(sourceId));
    for (const medium of ['water', 'sun', 'salt']) {
      assert.ok(['safe', 'caution', 'avoid'].includes(stone.care[medium].status));
      assert.ok(stone.care[medium].detail.length > 20);
    }
  }
});

test('generated snippets keep the useful content in indexable HTML', () => {
  for (const file of generatedFiles) {
    const source = read(file);
    assert.match(source, /Generated by scripts\/build_owned_stone_assets\.py/);
    assert.doesNotMatch(source, /<script/i);
  }
  assert.equal((read(generatedFiles[0]).match(/data-stone-id=/g) || []).length, 8);
  assert.equal((read(generatedFiles[1]).match(/data-care-row/g) || []).length, 8);
  assert.equal((read(generatedFiles[2]).match(/data-month=/g) || []).length, 12);
  assert.equal((read(generatedFiles[3]).match(/data-atlas-entry/g) || []).length, 8);
});

test('sections are semantic, accessible and do not persist selector answers', () => {
  for (const [index, file] of sectionFiles.entries()) {
    const source = read(file);
    assert.match(source, /milaura-owned-stone-guides\.css/);
    assert.match(source, /render 'milaura-owned-hero'/);
    assert.match(source, new RegExp(`variant: '${heroVariants[index]}'`));
  }
  const hero = read(heroSnippet);
  assert.match(hero, /<h1/);
  assert.match(hero, /<picture/);
  assert.match(hero, /fetchpriority="high"/);
  for (const file of heroAssets) assert.ok(fs.statSync(path.join(root, file)).size > 100000, `${file} is missing or unexpectedly small`);
  const selector = read(sectionFiles[0]);
  assert.match(selector, /<fieldset>/);
  assert.match(selector, /aria-live="polite"/);
  assert.match(selector, /<noscript>/);
  const script = read('assets/milaura-owned-stone-guides.js');
  assert.doesNotMatch(script, /localStorage|sessionStorage|document\.cookie/);
});

test('study cannot display invented results by default', () => {
  assert.equal(data.study.status, 'protocol_ready_no_results');
  const template = JSON.parse(read('templates/page.milaura-study.json'));
  assert.equal(template.sections.main.settings.results_ready, false);
  const section = read('sections/milaura-owned-study.liquid');
  assert.match(section, /Aucun résultat n'est publié à ce stade/);
});

test('new UI files contain no hard-coded hex color and no em dash', () => {
  const files = [
    ...generatedFiles,
    heroSnippet,
    ...sectionFiles,
    'assets/milaura-owned-stone-guides.css',
    'assets/milaura-owned-stone-guides.js',
    'data/milaura-owned-stones.json'
  ];
  for (const file of files) {
    const source = read(file);
    assert.doesNotMatch(source, /#[0-9a-f]{3,8}\b/i, `${file} contains a hard-coded color`);
    assert.doesNotMatch(source, /\u2014/, `${file} contains an em dash`);
  }
});
