#!/usr/bin/env python3
"""Validate the owned-stone dataset and generate indexable Liquid fragments."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "milaura-owned-stones.json"
GENERATED_HEADER = "{% comment %}Generated by scripts/build_owned_stone_assets.py. Do not edit by hand.{% endcomment %}\n"


def esc(value: object, *, quote: bool = True) -> str:
    return html.escape(str(value), quote=quote)


def liquid_route(url: str) -> str:
    if url.startswith("/collections/"):
        return "{{ routes.collections_url }}/" + esc(url.removeprefix("/collections/"))
    if url.startswith("/pages/"):
        return "{{ routes.pages_url }}/" + esc(url.removeprefix("/pages/"))
    return esc(url)


def load_data() -> dict:
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def validate(data: dict) -> None:
    errors: list[str] = []
    sources = data.get("sources", [])
    source_ids = [item.get("id") for item in sources]
    if len(source_ids) != len(set(source_ids)):
        errors.append("source ids must be unique")

    intentions = {item.get("id") for item in data.get("intentions", [])}
    colors = {item.get("id") for item in data.get("colors", [])}
    stones = data.get("stones", [])
    stone_ids = [item.get("id") for item in stones]
    if len(stone_ids) != len(set(stone_ids)):
        errors.append("stone ids must be unique")
    if len(stones) < 8:
        errors.append("at least eight commercial stones are required")

    for stone in stones:
        stone_id = stone.get("id", "<missing>")
        required = (
            "display_name",
            "family",
            "hardness",
            "symbolic_summary",
            "visual_summary",
            "image_url",
            "image_alt",
            "primary_collection_url",
            "primary_collection_label",
            "care",
            "atlas",
            "source_ids",
        )
        for key in required:
            if not stone.get(key):
                errors.append(f"{stone_id}: missing {key}")
        unknown_intentions = set(stone.get("intentions", [])) - intentions
        unknown_colors = set(stone.get("colors", [])) - colors
        unknown_sources = set(stone.get("source_ids", [])) - set(source_ids)
        if unknown_intentions:
            errors.append(f"{stone_id}: unknown intentions {sorted(unknown_intentions)}")
        if unknown_colors:
            errors.append(f"{stone_id}: unknown colors {sorted(unknown_colors)}")
        if unknown_sources:
            errors.append(f"{stone_id}: unknown sources {sorted(unknown_sources)}")
        if not str(stone.get("image_url", "")).startswith("https://cdn.shopify.com/"):
            errors.append(f"{stone_id}: image must reuse a Shopify CDN asset")
        if not str(stone.get("primary_collection_url", "")).startswith("/collections/"):
            errors.append(f"{stone_id}: invalid primary collection URL")
        for medium in ("water", "sun", "salt"):
            care = stone.get("care", {}).get(medium, {})
            if care.get("status") not in {"safe", "caution", "avoid"}:
                errors.append(f"{stone_id}: invalid {medium} status")
            if not care.get("label") or not care.get("detail"):
                errors.append(f"{stone_id}: incomplete {medium} guidance")

    birthstones = data.get("birthstones", [])
    months = [item.get("month") for item in birthstones]
    if months != list(range(1, 13)):
        errors.append("birthstones must contain months 1 through 12 in order")

    study = data.get("study", {})
    if study.get("status") != "protocol_ready_no_results":
        errors.append("study must remain in protocol_ready_no_results until real results exist")
    if set(study.get("source_ids", [])) - set(source_ids):
        errors.append("study contains unknown source ids")

    if errors:
        raise ValueError("\n".join(errors))


def remote_image(url: str, alt: str, css_class: str, sizes: str) -> list[str]:
    connector = "&" if "?" in url else "?"
    base = f"{url}{connector}"
    return [
        "{% # theme-check-disable RemoteAsset %}",
        f'<img class="{css_class}" src="{esc(base)}width=800"',
        f'  srcset="{esc(base)}width=360 360w, {esc(base)}width=560 560w, {esc(base)}width=800 800w"',
        f'  sizes="{esc(sizes)}" alt="{esc(alt)}" width="800" height="800" loading="lazy">',
        "{% # theme-check-enable RemoteAsset %}",
    ]


def render_selector(data: dict) -> str:
    lines = [GENERATED_HEADER.rstrip(), '<div class="milaura-owned-selector__results" data-stone-results>']
    for index, stone in enumerate(data["stones"]):
        attrs = (
            f'data-stone-id="{esc(stone["id"])}" '
            f'data-intentions="{esc(" ".join(stone["intentions"]))}" '
            f'data-colors="{esc(" ".join(stone["colors"]))}" '
            f'data-care="{esc(stone["care_ease"])}" '
            f'data-default-order="{index}"'
        )
        lines.append(f'  <article class="milaura-owned-selector__stone" {attrs}>')
        lines.append('    <a class="milaura-owned-selector__media" href="{}" tabindex="-1" aria-hidden="true">'.format(liquid_route(stone["primary_collection_url"])))
        lines.extend(f"      {line}" for line in remote_image(stone["image_url"], stone["image_alt"], "milaura-owned-selector__image", "(max-width: 749px) 44vw, 26vw"))
        lines.append("    </a>")
        lines.append('    <div class="milaura-owned-selector__copy">')
        lines.append(f'      <h3>{esc(stone["display_name"])}</h3>')
        lines.append(f'      <p class="milaura-owned-selector__family">{esc(stone["family"])}</p>')
        lines.append(f'      <p>{esc(stone["symbolic_summary"])}</p>')
        lines.append(f'      <a class="milaura-owned-link" href="{liquid_route(stone["primary_collection_url"])}">{esc(stone["primary_collection_label"])}</a>')
        lines.append("    </div>")
        lines.append("  </article>")
    lines.append("</div>")
    return "\n".join(lines) + "\n"


def render_care(data: dict) -> str:
    lines = [GENERATED_HEADER.rstrip()]
    for stone in data["stones"]:
        lines.append(f'<tr data-care-row data-stone-search="{esc(stone["display_name"].lower())}">')
        lines.append('  <th scope="row">')
        lines.append(f'    <a href="#{esc(stone["id"])}">{esc(stone["display_name"])}</a>')
        lines.append(f'    <span>{esc(stone["family"])}, Mohs {esc(stone["hardness"])}</span>')
        lines.append("  </th>")
        for medium in ("water", "sun", "salt"):
            care = stone["care"][medium]
            lines.append('  <td data-label="{}">'.format({"water": "Eau", "sun": "Soleil", "salt": "Sel"}[medium]))
            lines.append(f'    <span class="milaura-owned-status" data-status="{esc(care["status"])}">{esc(care["label"])}</span>')
            lines.append(f'    <span class="milaura-owned-status__detail">{esc(care["detail"])}</span>')
            lines.append("  </td>")
        lines.append("</tr>")
    return "\n".join(lines) + "\n"


def render_birthstones(data: dict) -> str:
    lines = [GENERATED_HEADER.rstrip(), '<div class="milaura-owned-birthstones__grid">']
    for item in data["birthstones"]:
        has_image = bool(item["image_url"])
        lines.append(f'  <article class="milaura-owned-birthstones__month" data-month="{item["month"]}">')
        lines.append('    <div class="milaura-owned-birthstones__month-heading">')
        lines.append(f'      <span aria-hidden="true">{item["month"]:02d}</span>')
        lines.append(f'      <h2>{esc(item["month_name"])}</h2>')
        lines.append("    </div>")
        if has_image:
            lines.append('    <div class="milaura-owned-birthstones__media">')
            lines.extend(f"      {line}" for line in remote_image(item["image_url"], item["image_alt"], "milaura-owned-birthstones__image", "(max-width: 749px) 42vw, 18vw"))
            lines.append("    </div>")
        else:
            lines.append('    <div class="milaura-owned-birthstones__media is-empty" aria-hidden="true"><span>MilAura</span></div>')
        lines.append(f'    <p class="milaura-owned-birthstones__names">{esc(" · ".join(item["stones"]))}</p>')
        lines.append(f'    <p class="milaura-owned-birthstones__availability">{esc(item["availability_note"])}</p>')
        if item["collection_url"]:
            lines.append(f'    <a class="milaura-owned-link" href="{liquid_route(item["collection_url"])}">Voir la sélection</a>')
        lines.append("  </article>")
    lines.append("</div>")
    return "\n".join(lines) + "\n"


def render_atlas(data: dict) -> str:
    lines = [GENERATED_HEADER.rstrip(), '<div class="milaura-owned-atlas__list">']
    for stone in data["stones"]:
        atlas = stone["atlas"]
        lines.append(f'  <article id="{esc(stone["id"])}" class="milaura-owned-atlas__entry" data-atlas-entry data-stone-search="{esc(stone["display_name"].lower())}">')
        lines.append('    <figure class="milaura-owned-atlas__media">')
        lines.extend(f"      {line}" for line in remote_image(stone["image_url"], stone["image_alt"], "milaura-owned-atlas__image", "(max-width: 749px) 92vw, 36vw"))
        lines.append(f'      <figcaption>Photographie d’une pièce MilAura : {esc(stone["image_alt"])}</figcaption>')
        lines.append("    </figure>")
        lines.append('    <div class="milaura-owned-atlas__copy">')
        lines.append(f'      <h2>{esc(stone["display_name"])}</h2>')
        lines.append(f'      <p class="milaura-owned-atlas__identity">{esc(stone["family"])}, dureté de Mohs {esc(stone["hardness"])}.</p>')
        lines.append(f'      <p>{esc(stone["visual_summary"])}</p>')
        lines.append('      <h3>Repères à observer</h3>')
        lines.append("      <ul>")
        lines.extend(f"        <li>{esc(cue)}</li>" for cue in atlas["look_for"])
        lines.append("      </ul>")
        lines.append('      <h3>Imitations ou confusions fréquentes</h3>')
        lines.append(f'      <p>{esc(", ".join(atlas["common_imitations"]))}.</p>')
        lines.append(f'      <p class="milaura-owned-atlas__limit">{esc(atlas["limit"])}</p>')
        lines.append(f'      <a class="milaura-owned-link" href="{liquid_route(stone["primary_collection_url"])}">{esc(stone["primary_collection_label"])}</a>')
        lines.append("    </div>")
        lines.append("  </article>")
    lines.append("</div>")
    return "\n".join(lines) + "\n"


def build_outputs(data: dict) -> dict[Path, str]:
    return {
        ROOT / "snippets" / "milaura-owned-selector-cards.liquid": render_selector(data),
        ROOT / "snippets" / "milaura-owned-care-rows.liquid": render_care(data),
        ROOT / "snippets" / "milaura-owned-birth-months.liquid": render_birthstones(data),
        ROOT / "snippets" / "milaura-owned-atlas-entries.liquid": render_atlas(data),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Validate generated files without writing")
    args = parser.parse_args()

    data = load_data()
    validate(data)
    outputs = build_outputs(data)

    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            raise SystemExit("Generated files are missing or stale:\n" + "\n".join(stale))
        print(f"PASS: {len(data['stones'])} stones, 12 months, {len(outputs)} generated snippets")
        return 0

    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
